services:
  db:
    image: mysql:5.7
    container_name: mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: soufiane_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "9906:3306"
  app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8083:3307'
      environment:
        PMA_HOST: db
  web:
    image: php:7.2.2-apache 
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true